FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install --silent --no-audit --no-fund

COPY tsconfig.json ./
COPY src/ ./src/

RUN npm run build

FROM node:20-alpine

WORKDIR /app

ENV NODE_ENV=production

COPY package*.json ./
RUN npm install --silent --no-audit --no-fund --production

COPY --from=build /app/dist ./dist

EXPOSE 3000

CMD ["node", "dist/server.js"]
